### ISSUE TITLE
Vim Plugin Error: Undefined variable g:ImportJSChannel

### ISSUE THREAD

**Issue by raffylopez** [Galooshi/vim-import-js#13]
![importjserr-vim](https://cloud.githubusercontent.com/assets/9276000/19188704/1879e7a0-8cc6-11e6-81b9-6b59d950df91.png)

**Comment by lencioni** [comment]
What version of Vim are you using? This plugin requires a relatively recent version.

We should document this requirement in the readme.

**Comment by raffylopez** [comment]
![vim-version](https://cloud.githubusercontent.com/assets/9276000/19211771/2c092900-8d77-11e6-8283-b33e24b30047.png)

**Comment by lencioni** [comment]
Yes, it looks like your version is too old. You are using vim v7.4.1403, but `ch_evalraw` (the function it is erroring out on) wasn't added until v7.4.1435. If you update Vim, does this resolve your issue?

**Comment by raffylopez** [comment]
Updated to Vim v8.0.0.3, and plugin's no longer producing original errors. However, I'm get a new error, "importjsd process not running".

![importjsd](https://cloud.githubusercontent.com/assets/9276000/19249064/12fe9256-8f66-11e6-9daa-521a26804d24.png)

**Comment by raffylopez** [comment]
Found the problem. As I am using Windows, I needed to attach .cmd to the job name.

// importjs.vim

```
let s:job=job_start(['importjsd', 'start', '--parent-pid', getpid()], {
    \'exit_cb': 'importjs#JobExit',
\})
```
into
```
let s:job=job_start(['importjsd.cmd', 'start', '--parent-pid', getpid()], {
    \'exit_cb': 'importjs#JobExit',
\})

```

**Comment by lencioni** [comment]
Ah interesting. I wonder if there's a way for us to modify this plugin to support both. If you have any suggestions, please post them here!

**Comment by billyvg** [comment]
I don't have a windows box to test, but I think we can use `has()` to determine if it's a Windows env and change the command arg

```
if has('win32') || has('win64')
endif
```
