### ISSUE TITLE
Error detected while processing function importjs#Init:

### ISSUE THREAD

**Issue by zirho** [Galooshi/vim-import-js#14]
Hello, thanks for the awesome plugin.

I have two osx machines, almost same neovim settings.

Working okay
NVIM 1.4.0
plugin manager: Vundle

Not working
NVIM 1.5.0
plugin manager: vim-plug

I am not sure this is about plugin manager or NVIM version.

below is from the one does not work.
Can you suggest a way to troubleshoot? 

Thanks

```
 ~/.config/nvim   master ●  vi
Error detected while processing function importjs#Init:
line    3:
E117: Unknown function: job_start
E15: Invalid expression: job_start(['importjsd', 'start', '--parent-pid', getpid()], {'exit_cb': 'importjs#JobExit',})
line    7:
E121: Undefined variable: s:job
E116: Invalid arguments for function job_getchannel(s:job)
E15: Invalid expression: job_getchannel(s:job)
Press ENTER or type command to continue
 ~/.config/nvim   master ●  vi -v
NVIM 0.1.5
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161007-26331-14gl0zw/neovim-0.1.5/build/config -I/tmp/neovim-20161007-26331-14gl0zw/neovim-0.1.5/src -I/tmp/neovim-20161007-26331-14gl0zw/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20161007-26331-14gl0zw/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20161007-26331-14gl0zw/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20161007-26331-14gl0zw/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20161007-26331-14gl0zw/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20161007-26331-14gl0zw/neovim-0.1.5/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20161007-26331-14gl0zw/neovim-0.1.5/build/src/nvim/auto -I/tmp/neovim-20161007-26331-14gl0zw/neovim-0.1.5/build/include
Compiled by zirho6@MBPro1.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.5/share/nvim"

 ~/.config/nvim   master ● 

```

**Comment by zirho** [comment]
It turned out it is plugin manager. 
junegunn/vim-plug this is actually popular one. 
https://github.com/junegunn/vim-plug
Can we consider supporting this?

Thanks!

**Comment by lencioni** [comment]
How did you determine that it was the plugin manager causing the problem? From your error message it looks to me like you are using a version of Vim that is too old and doesn't support the Vim features we are using here. What version of Vim are you using?

**Comment by tdooner** [comment]
I don't know if anyone has tested `vim-import-js` with neovim. Since the job control implementations have diverged, it seems unlikely to work without a little bit of extra work.

**Comment by zirho** [comment]
@lencioni I maybe wrong but I have almost same setup with different plugins manager. The one with other than vim-plug seems working fine. 
and as @tdooner said, it can be neovim. I'll put an update on this when I get a chance to look at. 

Thank you all.

**Comment by brunoti** [comment]
Same problem here with vim 7.4.898 and neovim 0.1.2, using Vundle.

**Comment by hpurmann** [comment]
Same problem with nvim 0.1.7 using `vim-plug`.

**Comment by aharris88** [comment]
Same problem with nvim 0.1.7 using vim-plug.

**Comment by nicklasnygren** [comment]
Same problem with nvim 0.1.7 using vim-plug.

**Comment by trotzig** [comment]
Sorry for leaving so many comments unanswered here. It looks like https://github.com/neovim/neovim/issues/5520 is relevant to the issue. Basically, neovim doesn't support the same channel interface as vim 8 does. If anyone is willing to take a stab at making the import-js plugin work for neovim, I'd be delighted to review a PR! If not, I'll try to get to it at a later time.

**Comment by aharris88** [comment]
I read the reddit thread on Neovim API comparison with Vim channels. Do you know how plugins are supposed to work with both Neovim and Vim? Do you have to do a check to see if it's running in Neovim and do one thing, or if it's in Vim, do another thing instead?

**Comment by trotzig** [comment]
I don't know to be honest, but it looks like `if has('nvim')` might do the trick. https://github.com/neovim/neovim/issues/1931

We could also look into some kind of feature detection instead of detecting what editor is running.

Do you have a link to the reddit thread?

**Comment by aharris88** [comment]
https://www.reddit.com/r/neovim/comments/58nrwv/neovim_api_comparison_with_vim_channels/
