### ISSUE TITLE
Works only once in macvim

### ISSUE THREAD

**Issue by valerybugakov** [Galooshi/vim-import-js#23]
Hey, awesome plugin! Works great in vim, but `<Leader>i` works only once in MacVim. On the second attempt to run this command an error is thrown.

<img width="1440" alt="screen shot 2017-07-18 at 5 42 24 am" src="https://user-images.githubusercontent.com/3846380/28296898-039c696c-6b7c-11e7-9a1f-f355bcf3da39.png">

**Comment by trotzig** [comment]
Ouch, that's annoying. Can you try following [the instructions listed under "Troubleshooting"](https://github.com/Galooshi/vim-import-js#troubleshooting) and see if there's anything useful in the logs?

**Comment by valerybugakov** [comment]
Somehow I've fixed it after reinstalling all the plugins.
