### ISSUE TITLE
Add support for import of styles.css

### ISSUE THREAD

**Issue by Npahlfer** [Galooshi/vim-import-js#29]
The plugin works as expected except for css files.
I import my css in react and use them like this:
`<div className={styles.wrapper}>`

The css file is in the same directory as the .js file.

Would it be possible to add this kind of support?

**Comment by trotzig** [comment]
Right now, only javascript files (including related .jsx and stuff) are imported. I don't think adding other types would be terribly hard, but there hasn't been a strong case for it. I'd be happy reviewing (and helping out on) a PR adding support for this.

In the meantime, you can probably make use of [the `aliases` config option](https://github.com/Galooshi/import-js#aliases), adding something like this: 

```js
aliases: {
  styles: './{filename}.css',
}
```

Then whenever you import something named `styles`, import-js will add an `import styles from 'ComponentName.css';`.

**Comment by Npahlfer** [comment]
Thanks, I just realised I've only seen the vim side of importjs, there was more features on the other page!
