### ISSUE TITLE
Allow to exclude some paths from import lookup

### ISSUE THREAD

**Issue by slaweet** [Galooshi/vim-import-js#32]
I want to import `ActionBar` component and it is only once in my source code, but the tool finds it also in coverage reports. I need a way to exclude the `coverage` folder. 

```
ImportJS: Select module to import for `ActionBar`:
1: import ActionBar from '../actionBar';
2: import ActionBar from '../../../coverage/Chrome 59.0.3071 (Mac OS X 10.12.6)/components/actionBar';
3: import ActionBar from '../../../coverage/Chrome 60.0.3112 (Mac OS X 10.12.6)/src/components/actionBar';
4: import ActionBar from '../../../coverage/HeadlessChrome 0.0.0 (Mac OS X 10.12.6)/src/components/actionBar';
Type number a
```

**Comment by trotzig** [comment]
You should be able to exclude these through config: 

```
// .importjs.js
module.exports = {
  excludes: [
    './**/coverage/**',
  ],
};
```

(this is from memory, not actually tested). 

See https://github.com/Galooshi/import-js#excludes

**Comment by slaweet** [comment]
Works great, thank you @trotzig. Your response times are amazing. You have the best vim plugin ever 🥇  

A configuration section in your README.md with a link to https://github.com/Galooshi/import-js#configuration might be helpful.
