### ISSUE TITLE
E387: Match is on current line

### ISSUE THREAD

**Issue by jeremija** [Galooshi/vim-import-js#36]
I'm using Neovim v0.2.2 on Mac OS High Sierra. Whenever I run `:ImportJSWord` for `Sequelize` I get the following error:

```
Error detected while processing function <SNR>40_JobHandler[2]..importjs#JoinNeovimOutput[11]..importjs#HandleJoinedNeovimInput
[2]..importjs#ParseResult[28]..importjs#Resolve:
line   11:
E387: Match is on current line
```

Which corresponds to the following line in the plugin code:

https://github.com/Galooshi/vim-import-js/blob/96447e48a89b65196d78005ce60fa2696489b31d/autoload/importjs.vim#L123

After I press `<CR>`, the expected prompt is shown:

```
ImportJS: Select module to import for `Sequelize`:
1: import Sequelize from 'sequelize';
2: import { Sequelize } from 'sequelize';
Type number and <Enter> or click with mouse (empty cancels):
```

If I remove the problematic line, the plugin still seems to continue to work (both `ImportJSFix` and `ImportJSWord` work). I'm not an expert in `vimscript` so I'm wondering what's the reason for that line? Can it be removed?

Thanks!

**Comment by trotzig** [comment]
The line is there to highlight the variable that you are currently importing. It looks like some vim versions will throw an error if you try to highlight a word that's on the same line which you are already on.

I added a try/catch to ignore that specific error, pushed in 9bf5358. Thanks for the report!
