### ISSUE TITLE
importjs process not running

### ISSUE THREAD

**Issue by alanhamlett** [Galooshi/vim-import-js#37]
Getting this error, tried re-installing `importjs` globally with no change:

```
==== start log session ====
  5.288031 : ERROR: Error detected while processing function importjs#Goto[5]..importjs#ExecCommand:
  5.288230 : ERROR: line   18:
  5.288273 : ERROR: importjs process not running
  5.288338 : looking for messages on channels
```

**Comment by trotzig** [comment]
If you run `importjs` outside of vim, what's the result/console output?

**Comment by alanhamlett** [comment]
```
$ importjs

  Usage: importjs [options] [command]
...
```

**Comment by trotzig** [comment]
And if you run `importjs start`? (this is what the vim plugin does under the hood)

**Comment by alanhamlett** [comment]
```
$ importjs start
ImportJS (v2.10.0) DAEMON active. Logs will go to: /var/folders/by/mnf1fcpd4wj9wvzv5dg4m2yh0000gn/T/importjs.log
```

**Comment by alanhamlett** [comment]
I started a new shell and now it's working, maybe something in that shell's path wasn't able to find importjs binary.

**Comment by jwworth** [comment]
I am able to reproduce this. Rolling back to an older version of import-js (3.1.0 to 3.0.0) resolved it. Not the longterm solution, but perhaps it will help someone in a similar situation.

**Comment by trotzig** [comment]
@jwworth what’s the output if you run `importjs` from the command-line (v 3.1.0)?

**Comment by jwworth** [comment]
```
$ importjs -V
3.1.0
$ importjs

  Usage: importjs [options] [command]

  Options:

    -V, --version                         output the version number
    -h, --help
...
```
