### ISSUE TITLE
import-js can't find inspect from Node's util module

### ISSUE THREAD

**Issue by coaxial** [Galooshi/vim-import-js#40]
I have set env to contain node in the .importjs.js configuration file.

But if I have `console.log(inspect(obj))` in my code, import-js won't find `inspect` and I have to add it manually. It should instead add `const { inspect } = require('util')`.

Using vim and node 8.11

```javascript
// .import-js.js
module.exports = {
  declarationKeyword: 'const',
  environments: ['node', 'jest', 'es2017'],
  importDevDependencies: true,
  sortImports: true,
};
```

```
No JS module to import for `inspect`
```

**Comment by trotzig** [comment]
That would be a good addition to the node environment. We would have to add a `namedExports` to this file for it to work:
https://github.com/Galooshi/import-js/blob/master/lib/environments/nodeEnvironment.js

**Comment by coaxial** [comment]
PR is here: https://github.com/Galooshi/import-js/pull/492

**Comment by trotzig** [comment]
Great, thanks!
