### ISSUE TITLE
does not work well with NVM

### ISSUE THREAD

**Issue by zirho** [Galooshi/vim-import-js#44]
I guess instances installed in different node versions collide with dependencies.

![image](https://user-images.githubusercontent.com/1251296/43442416-b554ddce-9452-11e8-9c1e-6b0e3797c8c5.png)
```
Error detected while processing function <SNR>245_JobHandler:
line    7:
import-js error: module.js:471     throw err;     ^  Error: Cannot find module '/
usr/local/lib/node_modules/import-js/node_modules/sqlite3/lib/binding/node-v48-da
rwin-x64/node_sqlite3.node'     at Function.Module._resolveFilename (module.js:46
9:15)     at Function.Module._load (module.js:417:25)     at Module.require (modu
le.js:497:17)     at require (internal/module.js:20:19)     at Object.<anonymous>
 (/usr/local/lib/node_modules/import-js/node_modules/sqlite3/lib/sqlite3.js:4:15)
     at Module._compile (module.js:570:32)     at Object.Module._extensions..js (
module.js:579:10)     at Module.load (module.js:487:32)     at tryModuleLoad (mod
ule.js:446:12)     at Function.Module._load (module.js:438:3)
```

reproducing it

1. install nvm 
2. install node 6 and 8
3. install import-js in both
4. try to use one of them

**Comment by dominikduda** [comment]
I am also experiencing this issue.

**Comment by zirho** [comment]
It turned out that it happens when you have importjs in multiple versions of nodes.
Cleaning them up and having one installed globally (throughout the all installed node versions) make it working again.

**Comment by dominikduda** [comment]
I also found that simply using importjs@3.0.0 fixes the issuel.

**Comment by trotzig** [comment]
Thanks for cycling back! I'm closing this as it looks like you found a workaround.

**Comment by galuh1300d** [comment]
> I also found that simply using importjs@3.0.0 fixes the issue.

I tried this, and still doesn't work
Do you have another solution?

**Comment by zirho** [comment]
This is whe you use `nvm` and install import-js in a different version of node or npm from where you installed import-js. uninstalling previous one and install import-js in the node environment where you want to use solves the problem.

**Comment by citravebriany** [comment]
> This is when you use `nvm` and install import-js in a different version of node or npm from where you installed import-js. uninstalling previous one and install import-js in the node environment where you want to use solves the problem.

i got this error too

Error detected while processing function importjs#Word[5]..importjs#ExecCommand[18]..importjs#TryExecPayload:
E631: ch_evalraw(): write failed
