### ISSUE TITLE
Error at the beginning on :ImportJSGoto (and probalby others) command

### ISSUE THREAD

**Issue by dagolinuxoid** [Galooshi/vim-import-js#48]
Sometimes I got an error after trying to jump to another file in my react project. Usually (as I remember)  it happens at the beginning, but as some time goes on everything works just fine. There is some logging:
```
 14.583151 on 0: Blocking NL read, timeout: 2000 msec
 14.583159 on 0: Waiting for up to 2000 msec
 14.713704 RECV on 0(out): 'ImportJS (v4.0.2) DAEMON active. Logs will go to: /tmp/importjs.log
'
 14.713723 on 0: Returning 67 bytes
 14.713889 : ERROR: Error detected while processing function importjs#Goto[5]..importjs#ExecCommand[26]..importjs#ParseResult:
 14.714096 : ERROR: line    1:
 14.714133 : ERROR: E474: Invalid argument
 14.714170 : ERROR: line    3:
 14.714187 : ERROR: E715: Dictionary required
 14.714223 : ERROR: line    8:
 14.714240 : ERROR: E715: Dictionary required
 14.714275 : ERROR: line   13:
 14.714291 : ERROR: E715: Dictionary required
 14.714629 : ERROR: line   24:
 14.714653 : ERROR: E715: Dictionary required
 14.714691 : ERROR: line   27:
 14.714707 : ERROR: E715: Dictionary required
```
I have *import-js 4.0.2* installed globally.

**Comment by dagolinuxoid** [comment]
I have some updates on the issue. I used the plugin *without* watchman software. `/tmp/importjs.log` had some complains and warnings about the fact. I installed the watchman via
```bash
$ git clone https://github.com/facebook/watchman.git -b v4.9.0 --depth 1
$ cd watchman 
$ ./autogen.sh
$ ./configure
$ make
$ sudo make install
```
I assume there is no need in further actions to setup *watchman* and *importjs* module (am I correct?) since the warnings from *importjs.log* disappeared at running `importjs start`. There is no error in vim too. The only concern I have is that sometimes it still a bit lagging in some occasions. `/tmp/importjs.log` file has these lines:
```
{"message":"Failed to resolve \"react-scripts\" relative to /home/linux/Documents/projects/react-way-of-samurai","level":"error"}
{"message":"Failed to resolve \"react-scripts\" relative to /home/linux/Documents/projects/react-way-of-samurai","level":"error"}
{"message":"Failed to resolve \"react-scripts\" relative to /home/linux/Documents/projects/react-way-of-samurai","level":"error"}

```

**Comment by trotzig** [comment]
> I assume there is no need in further actions to setup watchman and importjs module (am I correct?)

That's correct, import-js will detect and use an installed watchman binary automatically. 

I'm not sure why 'react-scripts' isn't found in your case, but it's probably safe to ignore.

**Comment by dagolinuxoid** [comment]
Yep I'm pretty satisfied at this point, but I was just curious about why in every project importjs.log prints the same Failed to resolve *react-scripts*

**Comment by dagolinuxoid** [comment]
I'm gonna close the issue since installing watchman solved the main problem. But if someone have encountered the errors about react-scripts in logging and was able to fix it feel free to drop a comment and mention me =)
